#! /usr/bin/env ruby
#
require 'orocos'
require 'optparse'
Orocos.initialize

gui = false
optparse = OptionParser.new do |opt|
    opt.banner = "run [--gui] DEVICE"
    opt.on '--gui', "starts the Rock task inspection widget on the running task" do
        gui = true
    end
end
io_port = *optparse.parse(ARGV)
if !io_port
    puts optparse
    exit 1
end

if gui
    require 'vizkit'
end

Orocos.run 'dvl_teledyne::Task' => 'dvl' do
    Orocos.logger.level = Logger::DEBUG
    puts "deployed the dvl_teledyne::Task task"

    dvl = Orocos::TaskContext.get 'dvl'
    dvl.io_port = io_port
    dvl.configure
    dvl.start

    if gui
        task_inspector = Vizkit.default_loader.task_inspector
        task_inspector.config(dvl)
        task_inspector.show
        Vizkit.exec
    else
        reader = dvl.bottom_tracking_samples.reader
        Orocos.watch(dvl) do
            if sample = reader.read
                pp sample
            end
        end
    end
end
