#! /usr/bin/env ruby
#
require 'orocos'
require 'optparse'
Orocos.initialize

gui = false
optparse = OptionParser.new do |opt|
    opt.on '--gui', "starts the Rock task inspection widget on the running task" do
        gui = true
    end
end

if gui
    require 'vizkit'
end


Orocos.run 'dvl_teledyne::Task' => 'dvl' do
    Orocos.logger.level = Logger::DEBUG
    puts "deployed the dvl_teledyne::Task task"

    dvl = Orocos::TaskContext.get 'dvl'
    dvl.io_port = ARGV[0]
    dvl.configure
    puts "configured the DVL"
    dvl.start

    puts
    puts
    puts
    puts "started pinging"
    if gui
    else
        Orocos.watch(dvl)
    end
end
